### ISSUE TITLE
Installing via `pip` don't include `template` folder.

### ISSUE THREAD

**Issue by ibrahim12** [DjangoAdminHackers/django-admin-row-actions#11]
I have installed with `pip`, it doesn't bring `templates` folder with it.

Installing from git works fine though.

**Comment by andybak** [comment]
Static doesn't come across either. I think we need to use a manifest file similar to how https://github.com/crccheck/django-object-actions handles it. God I hate Python packaging!

Pull requests gratefully accepted. I'll get around to it at some point but it's not top of my list as I always install as a pip editable src package.

**Comment by blag** [comment]
I might be able to get to this in a few days. Ping me if I forget.

**Comment by blag** [comment]
@midvik Got to it before I did. Fixed in #13.

I haven't pushed this fix to PyPI yet though. @andybak You okay with me pushing a release to PypI?

**Comment by andybak** [comment]
@blag - thanks a lot for tackling this. Go ahead and push to PyPI whenever you can.

**Comment by blag** [comment]
Pushed to PyPI as version 0.0.2.

**Comment by ibrahim12** [comment]
@blag Have you tested version 0.0.2 installing from PyPI ?. Just tried and found that static and templates folder are still missing on version 0.0.2. 

- Python Version 3.6.
